import type {StoryAct} from "@/types/story";
export const STORY_ACTS:StoryAct[]=[
{id:"market",number:"01",label:"THE MARKET",title:"The market is never silent.",description:"Every category is moving. Every audience leaves traces. The challenge is knowing which signals deserve attention.",sceneState:"market",kicker:"ACT I / MARKET FIELD"},
{id:"signal",number:"02",label:"THE SIGNAL",title:"The problem is knowing what matters.",description:"EIMAS turns fragmented activity into visible signals, separating movement from noise.",sceneState:"signal",kicker:"ACT II / SIGNAL DETECTION"},
{id:"pattern",number:"03",label:"THE PATTERN",title:"Signals become intelligence when they connect.",description:"Relationships emerge across demand, velocity, competition and behavior.",sceneState:"pattern",kicker:"ACT III / PATTERN FORMATION"},
{id:"opportunity",number:"04",label:"THE OPPORTUNITY",title:"Find the cluster worth a closer look.",description:"An example market signal becomes an opportunity hypothesis. It is a starting point for validation, not a fabricated market claim.",sceneState:"opportunity",kicker:"ACT IV / SIMULATED SIGNAL"},
{id:"engine",number:"05",label:"THE ENGINE",title:"Intelligence is a system, not a snapshot.",description:"Signals, context, pattern detection and validation work together to turn observation into a repeatable workflow.",sceneState:"intelligence",kicker:"ACT V / INTELLIGENCE ENGINE"},
{id:"magi",number:"06",label:"MAGI",title:"An intelligence layer that helps you investigate.",description:"MAGI is designed to observe, reason, use authorized tools, validate outputs and stop when the next action needs human judgment.",sceneState:"intelligence",kicker:"ACT VI / AGENT INTERFACE",cta:{label:"Talk to MAGI",href:"/magi"}},
{id:"decision",number:"07",label:"THE DECISION",title:"Intelligence is only valuable when it changes a decision.",description:"Move from a signal worth watching to a decision worth making—with evidence, context and clear uncertainty.",sceneState:"opportunity",kicker:"ACT VII / DECISION"},
{id:"system",number:"08",label:"THE SYSTEM",title:"See the market as a living system.",description:"The same intelligence layer can connect discovery, validation, opportunities, reports and future workflows.",sceneState:"intelligence",kicker:"ACT VIII / SYSTEM"},
{id:"enter",number:"09",label:"ENTER EIMAS",title:"Turn market signals into your next opportunity.",description:"Explore the intelligence system behind the story.",sceneState:"intelligence",kicker:"ACT IX / ENTRY POINT",cta:{label:"Explore EIMAS",href:"/explore"}}
];